name: Main

on:
  push:
    branches: main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.19.0
      - 
        name: Install
        run: npm i
      -
        name: Build
        run: npm run build
      -
        name: Test
        run: npm test
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: adamlarsonlee/tasqr-app:latest
      -
        name: Image Digest
        run: echo ${{ steps.docker_build.outputs.digest }}
